### ISSUE TITLE
No module named 'mmdet.ops.pairwise.pairwise_ext'

### ISSUE THREAD

**Issue by XJTU-Haolin** [LiWentomng/BoxInstSeg#4]
(openmmlab) @amax:/data0/ZHL/project/DET2D/rope2D/BoxInstSeg$ CUDA_VISIBLE_DEVICES=5 python tools/train.py configs/boxinst/boxinst_r50_fpn_1x_coco.py
Traceback (most recent call last):
  File "tools/train.py", line 17, in <module>
    from mmdet.apis import init_random_seed, set_random_seed, train_detector
  File "/data0/ZHL/project/DET2D/rope2D/BoxInstSeg/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/data0/ZHL/project/DET2D/rope2D/BoxInstSeg/mmdet/apis/inference.py", line 13, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "/data0/ZHL/project/DET2D/rope2D/BoxInstSeg/mmdet/datasets/__init__.py", line 9, in <module>
    from .utils import (NumClassCheckHook, get_loading_pipeline,
  File "/data0/ZHL/project/DET2D/rope2D/BoxInstSeg/mmdet/datasets/utils.py", line 11, in <module>
    from mmdet.models.roi_heads.mask_heads import FusedSemanticHead
  File "/data0/ZHL/project/DET2D/rope2D/BoxInstSeg/mmdet/models/__init__.py", line 7, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "/data0/ZHL/project/DET2D/rope2D/BoxInstSeg/mmdet/models/dense_heads/__init__.py", line 4, in <module>
    from .condinst_head import CondInstBoxHead, CondInstSegmHead, CondInstMaskBranch, CondInstMaskHead
  File "/data0/ZHL/project/DET2D/rope2D/BoxInstSeg/mmdet/models/dense_heads/condinst_head.py", line 14, in <module>
    from mmdet.ops.pairwise import pairwise_nlog
  File "/data0/ZHL/project/DET2D/rope2D/BoxInstSeg/mmdet/ops/pairwise/__init__.py", line 1, in <module>
    from .pairwise import pairwise_nlog
  File "/data0/ZHL/project/DET2D/rope2D/BoxInstSeg/mmdet/ops/pairwise/pairwise.py", line 3, in <module>
    from .pairwise_ext import pairwise_nlog_forward, pairwise_nlog_backward
ModuleNotFoundError: No module named 'mmdet.ops.pairwise.pairwise_ext'

Someone meet same problem? Where is pairwise_ext?

**Comment by LiWentomng** [comment]
@XJTU-Haolin  
Hello,  the pairwise  is a CUDA operation used for boxinst, which is needed to be compliled by the followings:

```
cd mmdet/ops/pairwise #compiling for the opeartion using in boxinst
python setup.py build develop 
cd mmdet/ops/tree_filter #compiling for the opeartion using in boxlevelset
python setup.py build develop
```

Or

`bash setup.sh`

**Comment by XJTU-Haolin** [comment]
> @XJTU-Haolin Hello, the pairwise is a CUDA operation used for boxinst, which is needed to be compliled by the followings:
> 
> ```
> cd mmdet/ops/pairwise #compiling for the opeartion using in boxinst
> python setup.py build develop 
> cd mmdet/ops/tree_filter #compiling for the opeartion using in boxlevelset
> python setup.py build develop
> ```
> 
> Or
> 
> `bash setup.sh`

It is nice of your help!
I have built but still met some other problems. I'll check later.

**Comment by amarnath-asteria** [comment]
any solution to the problem? i am getting the same error
