### ISSUE TITLE
ValueError: matrix contains invalid numeric entries

### ISSUE THREAD

**Issue by zhaoyangwei123** [LiWentomng/BoxInstSeg#6]
Hello, @LiWentomng 
I tried to reproduce your paper box2mask, but I had the following problems and the model had a very large loss at the beginning of training. How to solve it?

2023-01-07 12:27:40,129 - mmdet - INFO - Iter [50/368750]	lr: 5.000e-06, eta: 3 days, 14:44:25, time: 0.847, data_time: 0.050, memory: 6779, loss_cls: 9.3236, loss_project: 6.2381, loss_levelset: 0.0710, d0.loss_cls: 9.0557, d0.loss_project: 5.5436, d0.loss_levelset: 0.0670, d1.loss_cls: 9.3925, d1.loss_project: 5.5199, d1.loss_levelset: 0.0640, d2.loss_cls: 9.1847, d2.loss_project: 5.7577, d2.loss_levelset: 0.0549, d3.loss_cls: 9.3142, d3.loss_project: 5.8749, d3.loss_levelset: 0.0656, d4.loss_cls: 9.4000, d4.loss_project: 5.8713, d4.loss_levelset: 0.0596, d5.loss_cls: 9.0998, d5.loss_project: 6.2049, d5.loss_levelset: 0.0682, d6.loss_cls: 9.1544, d6.loss_project: 6.1733, d6.loss_levelset: 0.0779, d7.loss_cls: 9.0938, d7.loss_project: 6.3329, d7.loss_levelset: 0.0836, d8.loss_cls: 8.7211, d8.loss_project: 6.4827, d8.loss_levelset: 0.0856, loss: 152.4366, grad_norm: 307.3523

Traceback (most recent call last):
  File "./tools/train.py", line 242, in <module>
    main()
  File "./tools/train.py", line 231, in main
    train_detector(
  File "/home/ubuntu/wzy/BoxInstSeg/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ubuntu/miniconda3/envs/boxinstseg/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/ubuntu/miniconda3/envs/boxinstseg/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/ubuntu/miniconda3/envs/boxinstseg/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 63, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/ubuntu/wzy/BoxInstSeg/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/ubuntu/miniconda3/envs/boxinstseg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/miniconda3/envs/boxinstseg/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/home/ubuntu/wzy/BoxInstSeg/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/ubuntu/wzy/BoxInstSeg/mmdet/models/detectors/maskformer.py", line 104, in forward_train
    losses = self.panoptic_head.forward_train(x, img_metas, gt_bboxes,
  File "/home/ubuntu/wzy/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 440, in forward_train
    losses = self.loss(all_cls_scores, all_mask_preds, all_lst_feats,gt_labels, gt_masks,
  File "/home/ubuntu/miniconda3/envs/boxinstseg/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 205, in new_func
    return old_func(*args, **kwargs)
  File "/home/ubuntu/wzy/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 203, in loss
    losses_cls, loss_project, loss_levelset = multi_apply(
  File "/home/ubuntu/wzy/BoxInstSeg/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/ubuntu/wzy/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 239, in loss_single
    num_total_pos,num_total_neg) = self.get_targets(cls_scores_list, mask_preds_list,
  File "/home/ubuntu/wzy/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 142, in get_targets
    neg_inds_list) = multi_apply(self._get_target_single, cls_scores_list,
  File "/home/ubuntu/wzy/BoxInstSeg/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/ubuntu/wzy/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 167, in _get_target_single
    assign_result = self.assigner.assign(cls_score, mask_pred,
  File "/home/ubuntu/wzy/BoxInstSeg/mmdet/core/bbox/assigners/mask_hungarian_assigner.py", line 119, in assign
    matched_row_inds, matched_col_inds = linear_sum_assignment(cost)
ValueError: matrix contains invalid numeric entries

**Comment by LiWentomng** [comment]
Hello@zhaoyangwei123 
The large loss  is normal for box2mask.  I upload my training [log file](https://drive.google.com/file/d/14SvFTypqtx7TSMl3hw5VNNbV7vG0N9tc/view?usp=sharing) for coco (r-101). You can refer to it.

I didn't encounter the  above problem. It seems the problem of assigner.  Are you training for the COCO or your dataset?  I have test the codes and configs, which are normal for COCO and VOC.

**Comment by zhaoyangwei123** [comment]
@LiWentomng I am training for the coco on 8 NVIDIA RTX2080TI GPU. So I changed the image size from (1024, 1024) to (800, 800) with batch=1 and num_workers=0. I don't know if it's because I've changed these parameters.

**Comment by LiWentomng** [comment]
@zhaoyangwei123 
I suggest you firstly try VOC with RTX2080TI GPU.  VOC  needs the less GPU memory with less training time.  The VOC link with coco-format annotaions is [here](https://drive.google.com/file/d/16Mz13NSZBbhwPuRxiwi7ZA2Qvt9DaKtN/view).   

I guess that  `batch_size=1` may incur this problem.  I will check this problem.

**Comment by LiWentomng** [comment]
@zhaoyangwei123 
I have fixed this issue.   When batch_size=1,  the loss  values will  appear `nan ` value. 
 You can try the current codes.  Please note  when batch_size=1, the learning rate  `lr` and  training `step `and `max_iters` (50e by default)  need to be changed proportionally. 
Any further questions can be disscuessed.

**Comment by zhaoyangwei123** [comment]
@LiWentomng 
Thank you very much for your answer, but when I run your new code, I have the following problem：
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/boxinstseg/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/ubuntu/wzy/BoxInstSeg/BoxInstSeg-main/mmdet/datasets/pipelines/transforms.py", line 767, in __init__
    assert crop_size[0] > 0 and crop_size[1] > 0
TypeError: '>' not supported between instances of 'tuple' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/boxinstseg/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/ubuntu/wzy/BoxInstSeg/BoxInstSeg-main/mmdet/datasets/custom.py", line 129, in __init__
    self.pipeline = Compose(pipeline)
  File "/home/ubuntu/wzy/BoxInstSeg/BoxInstSeg-main/mmdet/datasets/pipelines/compose.py", line 23, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/home/ubuntu/miniconda3/envs/boxinstseg/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: RandomCrop: '>' not supported between instances of 'tuple' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 218, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/ubuntu/wzy/BoxInstSeg/BoxInstSeg-main/mmdet/datasets/builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/ubuntu/miniconda3/envs/boxinstseg/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CocoDataset: RandomCrop: '>' not supported between instances of 'tuple' and 'int'

I verified boxlevelset and boxinst, both work fine, so I think there may be some errors in the box2mask code you uploaded.

**Comment by LiWentomng** [comment]
@zhaoyangwei123 
When did this erro appear? At the starting or during training process?  
I have test the code and config with `800x800`  and `bs=1`, and the training work fine.
According to the reporting error,   the format of image size is right  as `image_size = (800, 800)` in your config  ?
Can you share your config information?

**Comment by zhaoyangwei123** [comment]
@LiWentomng
Hello, my error came at the beginning of the training and I have the following config,image_size = (1024,1024), samples_per_gpu=1, workers_per_gpu=0,  lr=0.00005.  The other configuration is unchanged.
Because I found that there are errors reported on multiple GPUs, I considered solving the problem on a single GPU first. On a single 2080TI, the image size can be changed without change.
I located the error in line 767 of transforms.py

In addition to trying your newly uploaded code with batch=1, I ran your previous code on four V100 GPUs. 
The previous problem with Nan on loss, you said it was because batch=1, but I still got the same error during training on v100 with batch=2, numworkers and other configurations unchanged and only changing the learning rate (I used the old code before not the latest code you uploaded, the new uploaded code I only tried training on 2080ti).
Here is the error reported on the v100GPU (previous code):

2023-01-09 23:59:57,557 - mmdet - INFO - Iter [9750/368750]	lr: 5.000e-06, eta: 4 days, 2:56:41, time: 0.944, data_time: 0.029, memory: 14530, loss_cls: 1.7945, loss_project: 1.2005, loss_levelset: 0.1374, d0.loss_cls: 3.7830, d0.loss_project: 1.3551, d0.loss_levelset: 0.1469, d1.loss_cls: 2.0516, d1.loss_project: 1.2665, d1.loss_levelset: 0.1401, d2.loss_cls: 1.8742, d2.loss_project: 1.1870, d2.loss_levelset: 0.1403, d3.loss_cls: 1.8293, d3.loss_project: 1.1677, d3.loss_levelset: 0.1394, d4.loss_cls: 1.8151, d4.loss_project: 1.1670, d4.loss_levelset: 0.1389, d5.loss_cls: 1.7782, d5.loss_project: 1.1886, d5.loss_levelset: 0.1381, d6.loss_cls: 1.7918, d6.loss_project: 1.1604, d6.loss_levelset: 0.1386, d7.loss_cls: 1.7839, d7.loss_project: 1.1765, d7.loss_levelset: 0.1381, d8.loss_cls: 1.7571, d8.loss_project: 1.2137, d8.loss_levelset: 0.1387, loss: 33.7384, grad_norm: 197.6207

File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/apis/train.py", line 244, in train_detector
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/apis/train.py", line 244, in train_detector
    train_detector(
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/apis/train.py", line 244, in train_detector
    main()
  File "./tools/train.py", line 231, in main
    train_detector(
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    runner.run(data_loaders, cfg.workflow)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    runner.run(data_loaders, cfg.workflow)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    runner.run(data_loaders, cfg.workflow)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 64, in train
    iter_runner(iter_loaders[i], **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 64, in train
    iter_runner(iter_loaders[i], **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 63, in train_step
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 63, in train_step
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 63, in train_step
    iter_runner(iter_loaders[i], **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 63, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
      File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/detectors/base.py", line 248, in train_step
output = self.module.train_step(*inputs[0], **kwargs[0])
      File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/detectors/base.py", line 248, in train_step
output = self.module.train_step(*inputs[0], **kwargs[0])
      File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/detectors/base.py", line 248, in train_step
output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
        losses = self(**data)losses = self(**data)

  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    losses = self(**data)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return forward_call(*input, **kwargs)
      File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
return forward_call(*input, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/detectors/base.py", line 172, in forward
    return old_func(*args, **kwargs)    
return old_func(*args, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/detectors/base.py", line 172, in forward
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/detectors/maskformer.py", line 104, in forward_train
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/detectors/maskformer.py", line 104, in forward_train
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/detectors/maskformer.py", line 104, in forward_train
    return forward_call(*input, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/detectors/maskformer.py", line 104, in forward_train
    losses = self.panoptic_head.forward_train(x, img_metas, gt_bboxes,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 440, in forward_train
    losses = self.panoptic_head.forward_train(x, img_metas, gt_bboxes,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 440, in forward_train
    losses = self.panoptic_head.forward_train(x, img_metas, gt_bboxes,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 440, in forward_train
    losses = self.panoptic_head.forward_train(x, img_metas, gt_bboxes,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 440, in forward_train
    losses = self.loss(all_cls_scores, all_mask_preds, all_lst_feats,gt_labels, gt_masks,
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 205, in new_func
    losses = self.loss(all_cls_scores, all_mask_preds, all_lst_feats,gt_labels, gt_masks,
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 205, in new_func
    losses = self.loss(all_cls_scores, all_mask_preds, all_lst_feats,gt_labels, gt_masks,
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 205, in new_func
    return old_func(*args, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 203, in loss
    return old_func(*args, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 203, in loss
    return old_func(*args, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 203, in loss
    losses_cls, loss_project, loss_levelset = multi_apply(
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/core/utils/misc.py", line 30, in multi_apply
    losses_cls, loss_project, loss_levelset = multi_apply(
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/core/utils/misc.py", line 30, in multi_apply
    losses_cls, loss_project, loss_levelset = multi_apply(
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/core/utils/misc.py", line 30, in multi_apply
    losses = self.loss(all_cls_scores, all_mask_preds, all_lst_feats,gt_labels, gt_masks,
  File "/data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 205, in new_func
    return old_func(*args, **kwargs)
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 203, in loss
    losses_cls, loss_project, loss_levelset = multi_apply(
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 239, in loss_single
    return tuple(map(list, zip(*map_results)))
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 239, in loss_single
    return tuple(map(list, zip(*map_results)))
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 239, in loss_single
    num_total_pos,num_total_neg) = self.get_targets(cls_scores_list, mask_preds_list,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 142, in get_targets
    num_total_pos,num_total_neg) = self.get_targets(cls_scores_list, mask_preds_list,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 142, in get_targets
    num_total_pos,num_total_neg) = self.get_targets(cls_scores_list, mask_preds_list,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 142, in get_targets
    neg_inds_list) = multi_apply(self._get_target_single, cls_scores_list,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/core/utils/misc.py", line 30, in multi_apply
    neg_inds_list) = multi_apply(self._get_target_single, cls_scores_list,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/core/utils/misc.py", line 30, in multi_apply
    neg_inds_list) = multi_apply(self._get_target_single, cls_scores_list,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 167, in _get_target_single
    return tuple(map(list, zip(*map_results)))
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 167, in _get_target_single
    return tuple(map(list, zip(*map_results)))
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 167, in _get_target_single
    assign_result = self.assigner.assign(cls_score, mask_pred,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/core/bbox/assigners/mask_hungarian_assigner.py", line 119, in assign
    assign_result = self.assigner.assign(cls_score, mask_pred,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/core/bbox/assigners/mask_hungarian_assigner.py", line 119, in assign
    assign_result = self.assigner.assign(cls_score, mask_pred,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/core/bbox/assigners/mask_hungarian_assigner.py", line 119, in assign
    return tuple(map(list, zip(*map_results)))
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 239, in loss_single
    num_total_pos,num_total_neg) = self.get_targets(cls_scores_list, mask_preds_list,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 142, in get_targets
    neg_inds_list) = multi_apply(self._get_target_single, cls_scores_list,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/models/dense_heads/box2mask_head.py", line 167, in _get_target_single
    assign_result = self.assigner.assign(cls_score, mask_pred,
  File "/data/huawei_share/pfchen20/work_dir/BoxInstSeg/mmdet/core/bbox/assigners/mask_hungarian_assigner.py", line 119, in assign
        matched_row_inds, matched_col_inds = linear_sum_assignment(cost)matched_row_inds, matched_col_inds = linear_sum_assignment(cost)
    
matched_row_inds, matched_col_inds = linear_sum_assignment(cost)
ValueError: matrix contains invalid numeric entriesValueError
: matrix contains invalid numeric entries
ValueError: matrix contains invalid numeric entries
    matched_row_inds, matched_col_inds = linear_sum_assignment(cost)
ValueError: matrix contains invalid numeric entries
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 108397) of binary: /data/huawei_share/pfchen20/work_dir/anaconda3/envs/boxinstseg1/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed

So I don't think the problem is necessarily a batch problem on the previous code and If in the new code you only change the error in the case of batch=1, it seems to me that it is not enough.

**Comment by zhaoyangwei123** [comment]
@LiWentomng 
Hello, my error came at the beginning of the training and I have the following config,image_size = (1024,1024), samples_per_gpu=1, workers_per_gpu=0, lr=0.00005. The other configuration is unchanged.
Because I found that there are errors reported on multiple GPUs, I considered solving the problem on a single GPU first. On a single 2080TI, the image size can be changed without change.
I located the error in line 767 of transforms.py
